

name: Release on Version 
on:
  push:
    tags: 
      - "v*"

jobs:
  build-for-ghcr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to GHCR
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build & push the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/modernews/led_control:${{github.ref_name}} |
           docker push --tag ghcr.io/modernews/:${{github.ref_name}}

